 version: "3.7"

 services:
    maildev:
      image: maildev/maildev
      container_name: maildev_docker_symfony
      command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
      ports:
        - "8081:80"
      restart: always
      networks:
          - dev
